services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongo
      - elastic

  redis:
    image: redis/redis-stack:7.2.0-v11

  mongo:
    image: mongodb/mongodb-community-server:5.0.14-ubi8

  elastic:
    image: elasticsearch:8.14.3

  kibana:
    image: kibana:8.14.3
    depends_on:
      - elastic
