services:
  redis:
    image: redis/redis-stack:7.2.0-v11
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - vMeet-development-network

  mongo:
    image: mongodb/mongodb-community-server:5.0.14-ubi8
    ports:
      - "27017:27017"
    networks:
      - vMeet-development-network

  elastic:
    image: elasticsearch:8.14.3
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - vMeet-development-network
    environment:
      discovery.type: single-node

  kibana:
    image: kibana:8.14.3
    ports:
      - "5601:5601"
    networks:
      - vMeet-development-network
    depends_on:
      - elastic

networks:
  vMeet-development-network:
    driver: bridge
